language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

env:
  - SYMFONY_VERSION=2.1.*
  - SYMFONY_VERSION=2.2.*
  - SYMFONY_VERSION=2.3.*
  - SYMFONY_VERSION=2.4.*

matrix:
  allow_failures:
    - php: hhvm

before_script:
  - composer require symfony/framework-bundle:${SYMFONY_VERSION} --prefer-source --no-update
  - composer require symfony/validator:${SYMFONY_VERSION} --prefer-source --no-update
  - composer require symfony/form:${SYMFONY_VERSION} --prefer-source --no-update
  - composer require symfony/twig-bundle:${SYMFONY_VERSION} --prefer-source --no-update
  - composer install --dev --prefer-source

notifications:
  email:
    - payumsupport@forma-pro.com
